# Generated by Django 4.2.24 on 2025-09-29 10:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('cost_price', models.FloatField()),
                ('sales_price', models.FloatField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.FloatField()),
                ('discount', models.FloatField(default=0.0)),
                ('is_weekend', models.BooleanField(default=False)),
                ('total_amount', models.FloatField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_os.menu')),
            ],
        ),
    ]
