# Generated by Django 5.2.7 on 2025-11-04 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_os', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Assign a manager to this branch', limit_choices_to={'role__in': ['manager', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='number_of_employees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
