# Generated by Django 4.2.24 on 2025-11-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_os', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='name',
            new_name='branch_name',
        ),
    ]
