# Generated by Django 4.2.24 on 2025-10-01 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_os', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='item_id',
            new_name='item',
        ),
    ]
