# Generated by Django 4.2.24 on 2025-10-21 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_os', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale Deduction'), ('restock', 'Restocking'), ('adjustment', 'Manual Adjustment'), ('waste', 'Waste/Spoilage'), ('return', 'Return to Supplier')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('previous_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('new_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('preparation_time', models.IntegerField(default=0, help_text='Time in minutes')),
                ('cooking_time', models.IntegerField(default=0, help_text='Time in minutes')),
                ('servings', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity needed per serving', max_digits=10)),
                ('unit', models.CharField(help_text='Should match inventory item unit', max_length=20)),
                ('is_optional', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['recipe', 'inventory_item'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sync_start', 'Sync Started'), ('sync_success', 'Sync Success'), ('sync_failure', 'Sync Failure'), ('auto_sync', 'Auto Sync'), ('manual_sync', 'Manual Sync')], max_length=20)),
                ('sales_synced', models.IntegerField(default=0)),
                ('sales_failed', models.IntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='possale',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='possale',
            name='is_offline_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='possale',
            name='offline_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='possale',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='possale',
            index=models.Index(fields=['offline_id'], name='restaurant__offline_b59f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='possale',
            index=models.Index(fields=['branch', 'created_at'], name='restaurant__branch__da0f63_idx'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='restaurant_os.branch'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_usages', to='restaurant_os.inventoryitem'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurant_os.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='menu_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='restaurant_os.menuitem'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='restaurant_os.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='inventory_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='restaurant_os.inventoryorder'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='pos_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='restaurant_os.possale'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'inventory_item')},
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['inventory_item', 'created_at'], name='restaurant__invento_49a2e2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='restaurant__transac_b794cd_idx'),
        ),
    ]
