# Generated by Django 5.2.7 on 2025-11-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_os', '0003_category_created_at_category_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='available',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Internal cost of the item', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Price shown to customers', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='preparation_time',
            field=models.PositiveIntegerField(default=5, help_text='Time in minutes'),
        ),
    ]
